package it.linksmt.cts2.plugin.sti.db.model;
// Generated 10.10.2012 15:20:29 by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CodeSystemVersionEntityMembership generated by hbm2java
 */
@Entity
@Table(name = "code_system_version_entity_membership"
)
public class CodeSystemVersionEntityMembership implements java.io.Serializable
{

  private CodeSystemVersionEntityMembershipId id;
  private CodeSystemVersion codeSystemVersion;
  private CodeSystemEntity codeSystemEntity;
  private Boolean isAxis;
  private Boolean isMainClass;
  private Long orderNr;

  public CodeSystemVersionEntityMembership()
  {
  }

  public CodeSystemVersionEntityMembership(final CodeSystemVersionEntityMembershipId id, final CodeSystemVersion codeSystemVersion, final CodeSystemEntity codeSystemEntity)
  {
    this.id = id;
    this.codeSystemVersion = codeSystemVersion;
    this.codeSystemEntity = codeSystemEntity;
  }

  public CodeSystemVersionEntityMembership(final CodeSystemVersionEntityMembershipId id, final CodeSystemVersion codeSystemVersion, final CodeSystemEntity codeSystemEntity, final Boolean isAxis, final Boolean isMainClass)
  {
    this.id = id;
    this.codeSystemVersion = codeSystemVersion;
    this.codeSystemEntity = codeSystemEntity;
    this.isAxis = isAxis;
    this.isMainClass = isMainClass;
  }

  public CodeSystemVersionEntityMembership(final Boolean isAxis, final Boolean isMainClass, final Long orderNr)
  {
    this.isAxis = isAxis;
    this.isMainClass = isMainClass;
    this.orderNr = orderNr;
  }



  public CodeSystemVersionEntityMembership copyObject()
  {
    return new CodeSystemVersionEntityMembership(isAxis, isMainClass, orderNr);
  }

  @EmbeddedId

  @AttributeOverrides(
          {
            @AttributeOverride(name = "codeSystemVersionId", column = @Column(name = "codeSystemVersionId", nullable = false)),
            @AttributeOverride(name = "codeSystemEntityId", column = @Column(name = "codeSystemEntityId", nullable = false))
          })
  public CodeSystemVersionEntityMembershipId getId()
  {
    return this.id;
  }

  public void setId(final CodeSystemVersionEntityMembershipId id)
  {
    this.id = id;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "codeSystemVersionId", nullable = false, insertable = false, updatable = false)
  public CodeSystemVersion getCodeSystemVersion()
  {
    return this.codeSystemVersion;
  }

  public void setCodeSystemVersion(final CodeSystemVersion codeSystemVersion)
  {
    this.codeSystemVersion = codeSystemVersion;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "codeSystemEntityId", nullable = false, insertable = false, updatable = false)
  public CodeSystemEntity getCodeSystemEntity()
  {
    return this.codeSystemEntity;
  }

  public void setCodeSystemEntity(final CodeSystemEntity codeSystemEntity)
  {
    this.codeSystemEntity = codeSystemEntity;
  }

  @Column(name = "isAxis")
  public Boolean getIsAxis()
  {
    return this.isAxis;
  }

  public void setIsAxis(final Boolean isAxis)
  {
    this.isAxis = isAxis;
  }

  @Column(name = "isMainClass")
  public Boolean getIsMainClass()
  {
    return this.isMainClass;
  }

  public void setIsMainClass(final Boolean isMainClass)
  {
    this.isMainClass = isMainClass;
  }

  @Column(name = "orderNr")
  public Long getOrderNr()
  {
    return orderNr;
  }

  public void setOrderNr(final Long orderNr)
  {
    this.orderNr = orderNr;
  }

}
