package it.linksmt.cts2.plugin.sti.importer.loinc;

public interface LoincFields {

	String LOINC_CODE_SYSTEM_NAME = "LOINC";

	String LOINC_ID = "id";
	String LOINC_NUM = "LOINC_NUM";

	String COMPONENT_IT = "COMPONENT_it";
	String COMPONENT_EN = "COMPONENT_en";

	String PROPERTY_IT = "PROPERTY_it";
	String PROPERTY_EN = "PROPERTY_en";

	String TIME_ASPECT_IT = "TIME_ASPECT_it";
	String TIME_ASPECT_EN = "TIME_ASPECT_en";

	String SYSTEM_IT = "SYSTEM_it";
	String SYSTEM_EN = "SYSTEM_en";

	String SCALE_TYP_IT = "SCALE_TYP_it";
	String SCALE_TYP_EN = "SCALE_TYP_en";

	String METHOD_TYP_IT = "METHOD_TYP_it";
	String METHOD_TYP_EN = "METHOD_TYP_en";

	String CLASS_IT = "CLASS_it";
	String CLASS_EN = "CLASS_en";

	String RELATEDNAMES2_IT = "RELATEDNAMES2_it";
	String RELATEDNAMES2_EN = "RELATEDNAMES2_en";

	String SHORTNAME_IT = "SHORTNAME_it";
	String SHORTNAME_EN = "SHORTNAME_en";

	String LONG_COMMON_NAME_IT = "LONG_COMMON_NAME_it";
	String LONG_COMMON_NAME_EN = "LONG_COMMON_NAME_en";

	String CHNG_TYPE = "CHNG_TYPE";
	String STATUS = "STATUS";

	String VERSION_FIRST_RELEASED = "VERSION_FIRST_RELEASED";
	String VERSION_LAST_CHANGED = "VERSION_LAST_CHANGED";

	String DEFINITION_DESCRIPTION = "DEFINITION_DESCRIPTION";
	String CONSUMER_NAME = "CONSUMER_NAME";

	String CLASS_TYPE = "CLASSTYPE";
	String UNITS_REQUIRED = "UNITSREQUIRED";
	String SUBMITTED_UNITS = "SUBMITTED_UNITS";

	String ORDER_OBS = "ORDER_OBS";
	String UNITS_AND_RANGE = "UNITS_AND_RANGE";
	String EXAMPLE_UNITS = "EXAMPLE_UNITS";

	String STATUS_REASON = "STATUS_REASON";
	String STATUS_TEXT = "STATUS_TEXT";
	String CHANGE_REASON_PUBLIC = "CHANGE_REASON_PUBLIC";

	String EXTERNAL_COPYRIGHT_NOTICE = "EXTERNAL_COPYRIGHT_NOTICE";

	String HL7_FIELD_SUBFIELD_ID = "HL7_FIELD_SUBFIELD_ID";
	String HL7_ATTACHMENT_STRUCTURE  = "HL7_ATTACHMENT_STRUCTURE";
	String VALID_HL7_ATTACHMENT_REQUEST = "VALID_HL7_ATTACHMENT_REQUEST";

	String MAP_TO = "MAP_TO";
	String MAP_TO_COMMENT = "MAP_TO_COMMENT";

	// Mapping codifiche locali
	String LOCAL_CODE = "LOCAL_CODE";
	String LOCAL_DESCRIPTION = "LOCAL_DESCRIPTION";

	String BATTERY_CODE = "BATTERY_CODE";
	String BATTERY_DESCRIPTION = "BATTERY_DESCRIPTION";

	String LOCAL_UNITS = "LOCAL_UNITS";

	// Lista codifiche locali disponibili
	String LOCAL_CODE_LIST = "LOCAL_CODE_LIST";
}
